### ISSUE TITLE
Drag and Drop updated Info

### ISSUE THREAD

**Issue by amitesh786** [RobK/nightwatchjs-drag-n-drop-example#2]
Drag and Drop feature was not working whatever you provided in drag-and-drop.js file. 
So I'll provide you my solution which was working fine in Chrome, Firefox and IE.
You have to install "html-dnd" using npm, as well as this is a link - https://www.npmjs.com/package/html-dnd
After installing you just have to execute this command - browser.execute(dragAndDrop, ['#draggable', '#droppable']);
Hope this will work fine for your test cases.

**Comment by chhavijain1205** [comment]
is this code is working.. i tried its not working on chrome

**Comment by amitesh786** [comment]
@chhavijain1205 - I have already provided you the solution, could you re-check this link - https://github.com/nightwatchjs/nightwatch/issues/956#issuecomment-383880421

**Comment by amitesh786** [comment]
I'm going to close this issue, because it works fine for different web browser.
